# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: 
      - master
      - development

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        java: [11]
    name: Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
      - run: mvn -f github-actions-java-maven/pom.xml clean compile
  build:
    runs-on: ubuntu-latest
    needs: compile
    name: Build Maven project
    steps:
      - uses: action/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java version: 11
      - name: Build and test project
        run: mvn -f github-actions-java-maven/pom.xml clean verify
      
        
      
        
